import fs from "node:fs";
import path from "node:path";
import JSZip from "jszip";
import Papa from "papaparse";
import { describe, expect, it } from "vitest";
import brandContractData from "@/data/brand-contract.json";
import { auditDeckAccuracy } from "@/lib/auditDeckAccuracy";
import type { BrandContract, DeckPlan } from "@/lib/deck-plan-schema";
import { approvedDeckRecipes } from "@/lib/deck-recipes";
import { generateDeckPlan, type AdoptionCsvRow } from "@/lib/generateDeckPlan";
import { auditPptxPackage } from "@/lib/pptx-package-audit";
import { renderPptx } from "@/lib/renderPptx";
import { validateDeckPlan } from "@/lib/validateDeckPlan";

const brandContract = brandContractData as unknown as BrandContract;
const qualityPrompt =
  "Create a high-quality executive adoption report using the loaded client data. Emphasize usage growth, workflow gaps, risk, and the next 90 days.";

function loadFixtureRows() {
  const csv = fs.readFileSync(
    path.join(process.cwd(), "data", "branddeck-test-client-adoption.csv"),
    "utf8"
  );
  const result = Papa.parse<AdoptionCsvRow>(csv, {
    header: true,
    skipEmptyLines: true,
    dynamicTyping: true
  });

  if (result.errors.length > 0) {
    throw new Error(result.errors.map((error) => error.message).join("; "));
  }

  return result.data;
}

function generateFixtureDeck(recipeId = "client_adoption_report") {
  return generateDeckPlan(qualityPrompt, loadFixtureRows(), brandContract, {
    recipeId
  });
}

function expectValidAndAccurate(deckPlan: DeckPlan) {
  const validation = validateDeckPlan(deckPlan, brandContract);
  const accuracy = auditDeckAccuracy({
    deckPlan,
    parsedCsvData: loadFixtureRows()
  });

  expect(validation.passed, validation.checks.filter((check) => !check.passed).map((check) => check.detail).join("\n")).toBe(true);
  expect(accuracy.passed, accuracy.checks.filter((check) => !check.passed).map((check) => check.detail).join("\n")).toBe(true);
}

describe("export quality gates", () => {
  it("keeps every brand-contract asset available for export", () => {
    const assets = brandContract.template_assets;

    if (!assets) {
      throw new Error("Expected template assets in the brand contract.");
    }

    const assetPaths = [
      assets.wordmark_black,
      assets.wordmark_white,
      assets.hero_photo,
      assets.texture_title,
      assets.texture_agenda,
      ...Object.values(assets.icons)
    ].filter((assetPath): assetPath is string => Boolean(assetPath));

    expect(assetPaths.length).toBeGreaterThanOrEqual(10);

    for (const assetPath of assetPaths) {
      const absolutePath = path.join(process.cwd(), "public", assetPath);
      const stats = fs.statSync(absolutePath);

      expect(stats.size, assetPath).toBeGreaterThan(0);
    }
  });

  it("generates valid, data-accurate plans for every approved deck recipe", () => {
    for (const recipe of approvedDeckRecipes) {
      const deckPlan = generateFixtureDeck(recipe.recipe_id);

      expect(deckPlan.deck_recipe_id).toBe(recipe.recipe_id);
      expect(deckPlan.slides.length).toBeGreaterThanOrEqual(
        recipe.slide_sequence.length
      );
      expectValidAndAccurate(deckPlan);
    }
  });

  it("renders a fallback PPTX with embedded brand media and a clean package audit", async () => {
    const deckPlan = generateFixtureDeck();
    const buffer = await renderPptx(deckPlan, brandContract);
    const zip = await JSZip.loadAsync(buffer);
    const mediaEntries = Object.keys(zip.files).filter((entry) =>
      entry.startsWith("ppt/media/")
    );
    const audit = await auditPptxPackage(buffer, deckPlan.slides.length);

    expect(buffer.byteLength).toBeGreaterThan(750000);
    expect(mediaEntries.length).toBeGreaterThanOrEqual(8);
    expect(audit.passed, JSON.stringify(audit, null, 2)).toBe(true);
  });

  it("rejects internal copy before export", () => {
    const deckPlan = generateFixtureDeck();
    deckPlan.slides[0].fields.subtitle =
      "Generated by BrandDeck using an OpenAI API model.";

    const validation = validateDeckPlan(deckPlan, brandContract);

    expect(validation.passed).toBe(false);
    expect(
      validation.checks.some(
        (check) => !check.passed && check.label === "Client copy boundary"
      )
    ).toBe(true);
  });

  it("catches placeholder leftovers in PPTX package audits", async () => {
    const deckPlan = generateFixtureDeck();
    const buffer = await renderPptx(deckPlan, brandContract);
    const zip = await JSZip.loadAsync(buffer);
    const slideOne = await zip.file("ppt/slides/slide1.xml")?.async("string");

    if (!slideOne) {
      throw new Error("Expected slide1.xml in rendered PPTX.");
    }

    zip.file("ppt/slides/slide1.xml", `${slideOne}\n<!-- Click to add -->`);

    const contaminatedBuffer = await zip.generateAsync({ type: "nodebuffer" });
    const audit = await auditPptxPackage(
      contaminatedBuffer,
      deckPlan.slides.length
    );

    expect(audit.passed).toBe(false);
    expect(audit.forbiddenPlaceholderHitCount).toBeGreaterThan(0);
  });
});
