import type {
  BrandContract,
  BrandLayoutDefinition,
  DeckPlan,
  DeckSlide
} from "@/lib/deck-plan-schema";

export type ValidationCheck = {
  id: string;
  label: string;
  passed: boolean;
  detail: string;
  slideTitle?: string;
};

export type ValidationReport = {
  passed: boolean;
  complianceScore: number;
  checks: ValidationCheck[];
  summary: {
    total: number;
    passed: number;
    failed: number;
  };
};

const FORBIDDEN_CLIENT_COPY_PATTERNS = [
  /\bOpenAI\b/i,
  /\bAPI\b/i,
  /\bmodel\b/i,
  /\bRecipe confidence\b/i,
  /\bPlanner:/i,
  /\bRenderer:/i,
  /\bprepared with\b/i,
  /\buser prompt priorities\b/i,
  /\blocal MVP\b/i,
  /\bMVP\b/i,
  /\bGenerated by BrandDeck\b/i,
  /\bBrand control\b/i,
  /\bSource context: no additional\b/i,
  /\btokens\b/i,
  /\beditable objects\b/i,
  /\bLorem ipsum\b/i,
  /\bClick to add\b/i,
  /\bThis chart is a placeholder\b/i,
  /\bCategory\s+\d+\b/i,
  /\bbrand kit\b/i,
  /\bbrand contract\b/i,
  /\bpresentation assurance\b/i,
  /\bevidence boundary\b/i,
  /\bapproved layout/i,
  /\bdeck plan\b/i,
  /\brendered from\b/i,
  /\bCSV\b/,
  /\bcreator request\b/i,
  // Stray foreign-script fragments are planner junk in this contract's
  // client copy (e.g. an orphaned "ほか" inside an English subtitle). The
  // planner sanitizer scrubs sparse fragments; anything that survives here
  // fails closed.
  /[\u3040-\u30FF\u3400-\u4DBF\u4E00-\u9FFF\uAC00-\uD7AF\uF900-\uFAFF\uFF66-\uFF9F]/
];

function stringifyField(value: unknown): string[] {
  if (value === null || value === undefined) {
    return [];
  }

  if (typeof value === "string") {
    return [value];
  }

  if (typeof value === "number" || typeof value === "boolean") {
    return [String(value)];
  }

  if (Array.isArray(value)) {
    return value.flatMap((item) => stringifyField(item));
  }

  if (typeof value === "object") {
    return Object.values(value as Record<string, unknown>).flatMap((item) =>
      stringifyField(item)
    );
  }

  return [];
}

function checkForbiddenClientCopy(slide: DeckSlide): ValidationCheck {
  const clientVisibleValues = [
    slide.title,
    ...Object.values(slide.fields).flatMap((value) => stringifyField(value))
  ];
  const matchedPattern = FORBIDDEN_CLIENT_COPY_PATTERNS.find((pattern) =>
    clientVisibleValues.some((value) => pattern.test(value))
  );

  return {
    id: `${slide.title}:client-copy-boundary`,
    label: "Client copy boundary",
    passed: !matchedPattern,
    detail: matchedPattern
      ? `Client-facing copy contains a forbidden/internal phrase matching ${matchedPattern}.`
      : "No internal, placeholder, model, or renderer phrases in client-facing fields.",
    slideTitle: slide.title
  };
}

function findLayout(
  brandContract: BrandContract,
  layoutId: DeckSlide["layout_id"]
): BrandLayoutDefinition | undefined {
  return brandContract.approved_layouts.find(
    (layout) => layout.layout_id === layoutId
  );
}

function checkRequiredPlaceholders(
  slide: DeckSlide,
  layout: BrandLayoutDefinition
): ValidationCheck[] {
  return layout.required_placeholders.map((placeholder) => {
    const value = slide.fields[placeholder];
    const hasValue =
      value !== undefined &&
      value !== null &&
      (!Array.isArray(value) || value.length > 0) &&
      (typeof value !== "string" || value.trim().length > 0);

    return {
      id: `${slide.title}:${placeholder}:required`,
      label: `Required placeholder: ${placeholder}`,
      passed: hasValue,
      detail: hasValue
        ? `${placeholder} is populated.`
        : `${placeholder} is missing or empty.`,
      slideTitle: slide.title
    };
  });
}

function checkTextLengths(
  slide: DeckSlide,
  layout: BrandLayoutDefinition
): ValidationCheck[] {
  const checks: ValidationCheck[] = [];
  const limits = layout.max_text_lengths;

  if (limits.title) {
    checks.push({
      id: `${slide.title}:title:length`,
      label: "Title length",
      passed: slide.title.length <= limits.title,
      detail: `${slide.title.length}/${limits.title} characters.`,
      slideTitle: slide.title
    });
  }

  Object.entries(slide.fields).forEach(([fieldName, value]) => {
    const limit =
      limits[fieldName] ??
      limits.metric_label ??
      limits.feature_label ??
      limits.label ??
      limits.note;

    if (!limit) {
      return;
    }

    const fieldValues = stringifyField(value);
    const longest = fieldValues.reduce(
      (max, fieldValue) => Math.max(max, fieldValue.length),
      0
    );

    checks.push({
      id: `${slide.title}:${fieldName}:length`,
      label: `Text length: ${fieldName}`,
      passed: longest <= limit,
      detail: `Longest value is ${longest}/${limit} characters.`,
      slideTitle: slide.title
    });
  });

  return checks;
}

function checkChartType(
  slide: DeckSlide,
  layout: BrandLayoutDefinition
): ValidationCheck | null {
  const chartType = slide.fields.chart_type;

  if (!chartType) {
    return null;
  }

  const requested = String(chartType);
  const passed = layout.approved_chart_types.includes(requested);

  return {
    id: `${slide.title}:chart_type`,
    label: "Approved chart type",
    passed,
    detail: passed
      ? `${requested} is approved for ${layout.layout_id}.`
      : `${requested} is not approved for ${layout.layout_id}.`,
    slideTitle: slide.title
  };
}

function checkSourceRefs(slide: DeckSlide): ValidationCheck {
  const refs = slide.source_refs ?? [];
  const allBounded = refs.every((ref) => ref.length <= 160);

  return {
    id: `${slide.title}:source_refs`,
    label: "Bounded source references",
    passed: refs.length === 0 || allBounded,
    detail:
      refs.length === 0
        ? "No source references attached."
        : `${refs.length} source reference${refs.length === 1 ? "" : "s"} attached within plan limits.`,
    slideTitle: slide.title
  };
}

export function validateDeckPlan(
  deckPlan: DeckPlan,
  brandContract: BrandContract
): ValidationReport {
  const checks: ValidationCheck[] = [];
  const approvedIds = new Set(
    brandContract.approved_layouts.map((layout) => layout.layout_id)
  );

  deckPlan.slides.forEach((slide) => {
    const layoutIsApproved = approvedIds.has(slide.layout_id);
    const layout = findLayout(brandContract, slide.layout_id);

    checks.push({
      id: `${slide.title}:layout`,
      label: "Approved layout ID",
      passed: layoutIsApproved,
      detail: layoutIsApproved
        ? `${slide.layout_id} is in the brand contract.`
        : `${slide.layout_id} is not in the brand contract.`,
      slideTitle: slide.title
    });
    checks.push(checkSourceRefs(slide));
    checks.push(checkForbiddenClientCopy(slide));

    if (!layout) {
      return;
    }

    checks.push(...checkRequiredPlaceholders(slide, layout));
    checks.push(...checkTextLengths(slide, layout));

    const chartCheck = checkChartType(slide, layout);
    if (chartCheck) {
      checks.push(chartCheck);
    }
  });

  const passedCount = checks.filter((check) => check.passed).length;
  const complianceScore =
    checks.length === 0 ? 0 : Math.round((passedCount / checks.length) * 100);

  return {
    passed: checks.every((check) => check.passed),
    complianceScore,
    checks,
    summary: {
      total: checks.length,
      passed: passedCount,
      failed: checks.length - passedCount
    }
  };
}
